"""chainroute CLI.

    chainroute init                                     scaffold chain.yaml + a starter plugins.py
    chainroute list                                      show the built-in plugins
    chainroute install --config config.yaml [--patch]    wire ChainRoute into a LiteLLM proxy config
    chainroute check --config config.yaml [--chain ...]   validate a chain against a litellm config
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import yaml

SHIM_NAME = "chainroute_callback"
SHIM = '''"""Generated by `chainroute install`.

LiteLLM loads callbacks from a .py file next to the proxy config (it does not import installed
packages), so this file re-exports the ChainRoute instance for it.
"""
from chainroute import instance  # noqa: F401
'''
CALLBACK_REF = SHIM_NAME + ".instance"

CHAIN_YAML_TEMPLATE = """\
# Plugins run top to bottom. Each entry is a RoutingPlugin: <module>.<ClassName>, plus whatever
# it needs under `with:`. See `chainroute list` for the built-ins, or plugins.py (scaffolded
# alongside this file) for a custom one -- reference it the same way, e.g. `use: plugins.MyPlugin`.
plugins:
  - use: chainroute.plugins.sticky_session.StickySession
"""

PLUGINS_PY_TEMPLATE = '''"""Your own chainroute plugins. Reference these from chain.yaml as `use: plugins.<ClassName>`
-- this file just needs to sit next to chain.yaml, no packaging or PYTHONPATH required.
"""
import datetime

from chainroute import RouteContext, RoutingPlugin


class BusinessHours(RoutingPlugin):
    """Outside business hours, prefer a cheaper deployment already in this same group. A
    minimal from-scratch example -- see chainroute.plugins for more (StickySession,
    KeywordRoute, BudgetGuard, ...)."""

    def configure(self, cheap_model: str = "gpt-4o-mini", start_hour: int = 9, end_hour: int = 18) -> None:
        self.cheap_model = cheap_model
        self.start_hour, self.end_hour = start_hour, end_hour

    async def apply(self, ctx: RouteContext, candidates: list) -> None:
        hour = datetime.datetime.now().hour
        if self.start_hour <= hour < self.end_hour:
            return  # business hours: no preference, let the rest of the chain / strategy decide
        for c in candidates:
            if c.model == self.cheap_model and not c.excluded:
                ctx.pin(c, "outside business hours: prefers %s" % self.cheap_model)
                return
'''


def _install(config: str, patch: bool) -> None:
    cfg = Path(config).resolve()
    if not cfg.exists():
        sys.exit("Config file not found: %s" % cfg)
    shim = cfg.parent / (SHIM_NAME + ".py")
    if not shim.exists() or shim.read_text() != SHIM:
        shim.write_text(SHIM)
    print("Wrote %s" % shim)

    text = cfg.read_text()
    if CALLBACK_REF in text:
        print("%s already references %s. Nothing to change." % (cfg.name, CALLBACK_REF))
        return

    manual = ("Add this to %s:\n\n  litellm_settings:\n    callbacks: %s\n\n"
              "(if you already have a `callbacks:` list, append %s to it)" % (cfg.name, CALLBACK_REF, CALLBACK_REF))
    if not patch:
        print(manual)
        print("\nOr re-run with --patch to edit the file for you (a .bak copy is kept).")
        return

    lines = text.splitlines()
    head = next((i for i, l in enumerate(lines) if re.match(r"^litellm_settings\s*:\s*(#.*)?$", l)), None)
    if head is None:
        new = text.rstrip("\n") + "\n\nlitellm_settings:\n  callbacks: %s\n" % CALLBACK_REF
    else:
        block_end = next((i for i in range(head + 1, len(lines))
                           if lines[i].strip() and not lines[i].startswith((" ", "\t", "#"))), len(lines))
        if any(re.match(r"^\s+callbacks\s*:", l) for l in lines[head + 1:block_end]):
            print("`litellm_settings.callbacks` already exists, so I won't guess how to merge.\n" + manual)
            return
        nxt = next((l for l in lines[head + 1:block_end] if l.strip() and not l.lstrip().startswith("#")), "  x")
        indent = nxt[: len(nxt) - len(nxt.lstrip())] or "  "
        lines.insert(head + 1, "%scallbacks: %s" % (indent, CALLBACK_REF))
        new = "\n".join(lines) + "\n"
    shutil.copyfile(cfg, str(cfg) + ".bak")
    cfg.write_text(new)
    print("Patched %s (backup: %s.bak). Restart the proxy to pick up the chain." % (cfg.name, cfg.name))


def _init(chain_path: str) -> None:
    chain = Path(chain_path)
    if chain.exists():
        print("%s already exists, leaving it alone." % chain)
    else:
        chain.write_text(CHAIN_YAML_TEMPLATE)
        print("Wrote %s" % chain)
    plugins_py = chain.parent / "plugins.py"
    if plugins_py.exists():
        print("%s already exists, leaving it alone." % plugins_py)
    else:
        plugins_py.write_text(PLUGINS_PY_TEMPLATE)
        print("Wrote %s" % plugins_py)
    print("\nNext: `chainroute install --config <your litellm config.yaml> --patch`, "
          "then edit %s to build your chain." % chain)


def _list_plugins() -> None:
    import sys
    from .plugins import BUILTINS
    for dotted, cls in BUILTINS.items():
        # each built-in documents itself at the top of its module, not on the class
        doc = getattr(sys.modules.get(cls.__module__), "__doc__", None) or cls.__doc__ or ""
        para = []
        for line in doc.strip().splitlines():
            if not line.strip():
                break
            para.append(line.strip())
        print("%s\n  %s\n" % (dotted, " ".join(para) or "(no description)"))


def _check(litellm_config: str, chain_path: str) -> None:
    from .loader import ChainConfigError, load_chain

    try:
        plugins = load_chain(chain_path)
    except ChainConfigError as e:
        sys.exit("chain error: %s" % e)
    print("Loaded %d plugin(s) from %s:" % (len(plugins), chain_path))
    for p in plugins:
        print("  - %s" % p.name)

    cfg_path = Path(litellm_config)
    if not cfg_path.exists():
        sys.exit("litellm config not found: %s" % cfg_path)
    doc = yaml.safe_load(cfg_path.read_text()) or {}
    model_list = [m for m in (doc.get("model_list") or []) if isinstance(m, dict)]
    groups = {m.get("model_name") for m in model_list}
    models_by_group: dict = {}
    for m in model_list:
        lp = m.get("litellm_params") or {}
        models_by_group.setdefault(m.get("model_name"), set()).add(str(lp.get("model", "")).rsplit("/", 1)[-1])
    print("\nModel groups in %s:" % cfg_path.name)
    for g in sorted(g for g in groups if g):
        print("  %s: %s" % (g, sorted(models_by_group.get(g, []))))

    referenced = {model for p in plugins for _, model in (getattr(p, "rules", None) or [])}
    all_models = {m for models in models_by_group.values() for m in models}
    missing = referenced - all_models
    if missing:
        print("\nWARNING: KeywordRoute references model(s) not present in any deployment: %s" % sorted(missing))
    elif referenced:
        print("\nEvery model KeywordRoute references exists in the litellm config.")


def main(argv=None) -> None:
    p = argparse.ArgumentParser(prog="chainroute")
    sub = p.add_subparsers(dest="cmd", required=True)

    ins = sub.add_parser("install", help="add ChainRoute to a LiteLLM proxy config")
    ins.add_argument("--config", default="config.yaml")
    ins.add_argument("--patch", action="store_true")

    init = sub.add_parser("init", help="scaffold chain.yaml and a starter plugins.py")
    init.add_argument("--chain", default="chain.yaml")

    sub.add_parser("list", help="show the built-in plugins")

    chk = sub.add_parser("check", help="validate a chain against a litellm config")
    chk.add_argument("--config", required=True, help="the litellm proxy config.yaml")
    chk.add_argument("--chain", default="chain.yaml")

    args = p.parse_args(argv)
    if args.cmd == "install":
        _install(args.config, args.patch)
    elif args.cmd == "init":
        _init(args.chain)
    elif args.cmd == "list":
        _list_plugins()
    elif args.cmd == "check":
        _check(args.config, args.chain)


if __name__ == "__main__":
    main()
