"""chainroute CLI.

    chainroute init                                     scaffold chain.yaml + a starter plugins.py
    chainroute list                                      show the built-in plugins
    chainroute install --config config.yaml [--patch]    wire ChainRoute into a LiteLLM proxy config
    chainroute check --config config.yaml [--chain ...]   validate a chain against a litellm config
    chainroute simulate --config c.yaml --group g --prompts p.jsonl   dry-run a chain, no LLM calls
"""
from __future__ import annotations

import argparse
import asyncio
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, Iterator, List

import yaml

SHIM_NAME = "chainroute_callback"
SHIM = '''"""Generated by `chainroute install`.

LiteLLM loads callbacks from a .py file next to the proxy config (it does not import installed
packages), so this file re-exports the ChainRoute instance for it.
"""
from chainroute import instance  # noqa: F401
'''
CALLBACK_REF = SHIM_NAME + ".instance"

CHAIN_YAML_TEMPLATE = """\
# Plugins run top to bottom. Each entry is a RoutingPlugin: <module>.<ClassName>, plus whatever
# it needs under `with:`. See `chainroute list` for the built-ins, or plugins.py (scaffolded
# alongside this file) for a custom one -- reference it the same way, e.g. `use: plugins.MyPlugin`.
plugins:
  - use: chainroute.plugins.sticky_session.StickySession
"""

PLUGINS_PY_TEMPLATE = '''"""Your own chainroute plugins. Reference these from chain.yaml as `use: plugins.<ClassName>`
-- this file just needs to sit next to chain.yaml, no packaging or PYTHONPATH required.
"""
import datetime

from chainroute import RouteContext, RoutingPlugin


class BusinessHours(RoutingPlugin):
    """Outside business hours, prefer a cheaper deployment already in this same group. A
    minimal from-scratch example -- see chainroute.plugins for more (StickySession,
    KeywordRoute, BudgetGuard, ...)."""

    def configure(self, cheap_model: str = "gpt-4o-mini", start_hour: int = 9, end_hour: int = 18) -> None:
        self.cheap_model = cheap_model
        self.start_hour, self.end_hour = start_hour, end_hour

    async def apply(self, ctx: RouteContext, candidates: list) -> None:
        hour = datetime.datetime.now().hour
        if self.start_hour <= hour < self.end_hour:
            return  # business hours: no preference, let the rest of the chain / strategy decide
        for c in candidates:
            if c.model == self.cheap_model and not c.excluded:
                ctx.pin(c, "outside business hours: prefers %s" % self.cheap_model)
                return
'''


def _install(config: str, patch: bool) -> None:
    cfg = Path(config).resolve()
    if not cfg.exists():
        sys.exit("Config file not found: %s" % cfg)
    shim = cfg.parent / (SHIM_NAME + ".py")
    if not shim.exists() or shim.read_text() != SHIM:
        shim.write_text(SHIM)
    print("Wrote %s" % shim)

    text = cfg.read_text()
    if CALLBACK_REF in text:
        print("%s already references %s. Nothing to change." % (cfg.name, CALLBACK_REF))
        return

    manual = ("Add this to %s:\n\n  litellm_settings:\n    callbacks: %s\n\n"
              "(if you already have a `callbacks:` list, append %s to it)" % (cfg.name, CALLBACK_REF, CALLBACK_REF))
    if not patch:
        print(manual)
        print("\nOr re-run with --patch to edit the file for you (a .bak copy is kept).")
        return

    lines = text.splitlines()
    head = next((i for i, l in enumerate(lines) if re.match(r"^litellm_settings\s*:\s*(#.*)?$", l)), None)
    if head is None:
        new = text.rstrip("\n") + "\n\nlitellm_settings:\n  callbacks: %s\n" % CALLBACK_REF
    else:
        block_end = next((i for i in range(head + 1, len(lines))
                           if lines[i].strip() and not lines[i].startswith((" ", "\t", "#"))), len(lines))
        if any(re.match(r"^\s+callbacks\s*:", l) for l in lines[head + 1:block_end]):
            print("`litellm_settings.callbacks` already exists, so I won't guess how to merge.\n" + manual)
            return
        nxt = next((l for l in lines[head + 1:block_end] if l.strip() and not l.lstrip().startswith("#")), "  x")
        indent = nxt[: len(nxt) - len(nxt.lstrip())] or "  "
        lines.insert(head + 1, "%scallbacks: %s" % (indent, CALLBACK_REF))
        new = "\n".join(lines) + "\n"
    shutil.copyfile(cfg, str(cfg) + ".bak")
    cfg.write_text(new)
    print("Patched %s (backup: %s.bak). Restart the proxy to pick up the chain." % (cfg.name, cfg.name))


def _init(chain_path: str) -> None:
    chain = Path(chain_path)
    if chain.exists():
        print("%s already exists, leaving it alone." % chain)
    else:
        chain.write_text(CHAIN_YAML_TEMPLATE)
        print("Wrote %s" % chain)
    plugins_py = chain.parent / "plugins.py"
    if plugins_py.exists():
        print("%s already exists, leaving it alone." % plugins_py)
    else:
        plugins_py.write_text(PLUGINS_PY_TEMPLATE)
        print("Wrote %s" % plugins_py)
    print("\nNext: `chainroute install --config <your litellm config.yaml> --patch`, "
          "then edit %s to build your chain." % chain)


def _list_plugins() -> None:
    import sys
    from .plugins import BUILTINS
    for dotted, cls in BUILTINS.items():
        # each built-in documents itself at the top of its module, not on the class
        doc = getattr(sys.modules.get(cls.__module__), "__doc__", None) or cls.__doc__ or ""
        para = []
        for line in doc.strip().splitlines():
            if not line.strip():
                break
            para.append(line.strip())
        print("%s\n  %s\n" % (dotted, " ".join(para) or "(no description)"))


def _read_litellm_config(litellm_config: str) -> Dict[str, Any]:
    cfg_path = Path(litellm_config)
    if not cfg_path.exists():
        sys.exit("litellm config not found: %s" % cfg_path)
    return yaml.safe_load(cfg_path.read_text()) or {}


def _model_list(doc: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [m for m in (doc.get("model_list") or []) if isinstance(m, dict)]


def _deployments_for_group(doc: Dict[str, Any], group: str) -> List[Dict[str, Any]]:
    """The raw litellm-shaped deployment dicts for one model_name -- what Chain.explain() (and,
    in the real proxy, async_filter_deployments) actually operates on. `model_info.id` is
    synthesized if the config didn't set one; it only needs to be stable within one simulate run."""
    out = []
    for i, m in enumerate(d for d in _model_list(doc) if d.get("model_name") == group):
        info = dict(m.get("model_info") or {})
        info.setdefault("id", "sim-%d" % i)
        out.append({"litellm_params": m.get("litellm_params") or {}, "model_info": info})
    return out


def _check(litellm_config: str, chain_path: str) -> None:
    from .loader import ChainConfigError, load_chain

    try:
        plugins = load_chain(chain_path)
    except ChainConfigError as e:
        sys.exit("chain error: %s" % e)
    print("Loaded %d plugin(s) from %s:" % (len(plugins), chain_path))
    for p in plugins:
        print("  - %s" % p.name)

    doc = _read_litellm_config(litellm_config)
    groups = {m.get("model_name") for m in _model_list(doc)}
    models_by_group: Dict[Any, set] = {}
    for m in _model_list(doc):
        lp = m.get("litellm_params") or {}
        models_by_group.setdefault(m.get("model_name"), set()).add(str(lp.get("model", "")).rsplit("/", 1)[-1])
    print("\nModel groups in %s:" % Path(litellm_config).name)
    for g in sorted(g for g in groups if g):
        print("  %s: %s" % (g, sorted(models_by_group.get(g, []))))

    referenced = {model for p in plugins for _, model in (getattr(p, "rules", None) or [])}
    all_models = {m for models in models_by_group.values() for m in models}
    missing = referenced - all_models
    if missing:
        print("\nWARNING: KeywordRoute references model(s) not present in any deployment: %s" % sorted(missing))
    elif referenced:
        print("\nEvery model KeywordRoute references exists in the litellm config.")


def _read_prompts(path: str) -> Iterator[Dict[str, Any]]:
    """One JSON value per line: a plain string is shorthand for {"messages": [{"role": "user",
    "content": <that string>}]}; an object can also set metadata/session_id for a fuller test."""
    with open(path) as f:
        for lineno, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError as e:
                sys.exit("%s:%d is not valid JSON: %s" % (path, lineno, e))
            if isinstance(value, str):
                yield {"messages": [{"role": "user", "content": value}]}
            elif isinstance(value, dict) and "messages" in value:
                yield value
            else:
                sys.exit("%s:%d must be a string or an object with a `messages` key" % (path, lineno))


def _simulate(litellm_config: str, group: str, chain_path: str, prompts_path: str, as_json: bool) -> None:
    from .loader import ChainConfigError, load_chain
    from .chain import Chain
    from .types import RouteContext

    try:
        chain = Chain(load_chain(chain_path))
    except ChainConfigError as e:
        sys.exit("chain error: %s" % e)

    doc = _read_litellm_config(litellm_config)
    deployments = _deployments_for_group(doc, group)
    if not deployments:
        sys.exit("no deployments under model_name '%s' in %s" % (group, litellm_config))

    async def run_one(prompt: Dict[str, Any]) -> Dict[str, Any]:
        ctx = RouteContext(model_group=group, requested_model=group, messages=prompt.get("messages"),
                            metadata=prompt.get("metadata") or {}, session_id=prompt.get("session_id"))
        return await chain.explain(ctx, deployments)

    for i, prompt in enumerate(_read_prompts(prompts_path), start=1):
        result = asyncio.run(run_one(prompt))
        if as_json:
            print(json.dumps({"i": i, "prompt": prompt, **result}))
            continue
        text = next((m.get("content", "") for m in reversed(prompt.get("messages") or [])
                     if m.get("role") == "user"), "")
        print("[%d] %r" % (i, text[:100]))
        if result["veto"]:
            print("  VETO: %s" % result["veto"])
        else:
            print("  %s" % result["decision"])
        names = ["%s/%s" % (c["provider"], c["model"]) for c in result["candidates"]]
        width = max((len(n) for n in names), default=0)
        for name, c in zip(names, result["candidates"]):
            print("    %-*s %s" % (width, name, _candidate_tag(c)))
        print()


def _candidate_tag(c: Dict[str, Any]) -> str:
    """A plugin that only biases (BanditRouter, WeightedCanary) narrows the field by score
    without ever setting `excluded` -- so this checks `survived`, not just `excluded`/`pinned`,
    or a losing bias-only candidate would misleadingly print as plain "eligible"."""
    if c["pinned"]:
        return "PINNED" + (" - %s" % c["reason"] if c["reason"] else "")
    if c["excluded"]:
        return "EXCLUDED - %s" % c["reason"]
    if not c["survived"]:
        return "NOT SELECTED" + (" - %s" % c["reason"] if c["reason"] else "")
    return ("SELECTED - %s" % c["reason"]) if c["reason"] else "eligible"


def main(argv=None) -> None:
    p = argparse.ArgumentParser(prog="chainroute")
    sub = p.add_subparsers(dest="cmd", required=True)

    ins = sub.add_parser("install", help="add ChainRoute to a LiteLLM proxy config")
    ins.add_argument("--config", default="config.yaml")
    ins.add_argument("--patch", action="store_true")

    init = sub.add_parser("init", help="scaffold chain.yaml and a starter plugins.py")
    init.add_argument("--chain", default="chain.yaml")

    sub.add_parser("list", help="show the built-in plugins")

    chk = sub.add_parser("check", help="validate a chain against a litellm config")
    chk.add_argument("--config", required=True, help="the litellm proxy config.yaml")
    chk.add_argument("--chain", default="chain.yaml")

    sim = sub.add_parser("simulate", help="dry-run a chain against sample prompts, no LLM calls")
    sim.add_argument("--config", required=True, help="the litellm proxy config.yaml, for its deployments")
    sim.add_argument("--group", required=True, help="the model_name (group) to simulate against")
    sim.add_argument("--chain", default="chain.yaml")
    sim.add_argument("--prompts", required=True, help="a JSONL file: one string or {messages: [...]} per line")
    sim.add_argument("--json", action="store_true", dest="as_json", help="one JSON result object per line")

    args = p.parse_args(argv)
    if args.cmd == "install":
        _install(args.config, args.patch)
    elif args.cmd == "init":
        _init(args.chain)
    elif args.cmd == "list":
        _list_plugins()
    elif args.cmd == "check":
        _check(args.config, args.chain)
    elif args.cmd == "simulate":
        _simulate(args.config, args.group, args.chain, args.prompts, args.as_json)


if __name__ == "__main__":
    main()
