"""Generated by `chainroute install`.

LiteLLM loads callbacks from a .py file next to the proxy config (it does not import installed
packages), so this file re-exports the ChainRoute instance for it.
"""
from chainroute import instance  # noqa: F401
